const listOfTrips = [
    {
      id: "1",
      name: "Mountain Adventure - Manali",
      image: require("../../assets/one.jpg"),
      startDate: "2025-03-10",
      endDate: "2025-03-15",
      itinerary: ["Day 1: Arrive & Explore Mall Road", "Day 2: Solang Valley", "Day 3: Rohtang Pass", "Day 4: Manikaran", "Day 5: Departure"],
      budget: "$800",
      transport: "Flight + Cab",
      accommodation: "Hotel Snow Heights",
      notes: "Pack warm clothes, adventure activities included.",
    },
    {
      id: "2",
      name: "Beach Getaway - Goa",
      image: require("../../assets/two.jpg"),
      startDate: "2025-04-05",
      endDate: "2025-04-10",
      itinerary: ["Day 1: North Goa Beaches", "Day 2: Dudhsagar Waterfalls", "Day 3: South Goa", "Day 4: Water Sports", "Day 5: Shopping & Departure"],
      budget: "$1000",
      transport: "Flight + Bike Rental",
      accommodation: "Beach Resort",
      notes: "Carry sunscreen, beachwear, and light clothing.",
    },
    {
      id: "3",
      name: "Desert Safari - Rajasthan",
      image: require("../../assets/three.jpg"),
      startDate: "2025-02-20",
      endDate: "2025-02-25",
      itinerary: ["Day 1: Jaipur City Tour", "Day 2: Jaisalmer Fort", "Day 3: Desert Safari", "Day 4: Udaipur", "Day 5: Departure"],
      budget: "$900",
      transport: "Train + Jeep Safari",
      accommodation: "Desert Camp + Hotel",
      notes: "Pack light, carry sunglasses & hats.",
    },
    {
      id: "4",
      name: "Hill Station Retreat - Ooty",
      image: require("../../assets/four.jpg"),
      startDate: "2025-06-01",
      endDate: "2025-06-07",
      itinerary: ["Day 1: Botanical Gardens", "Day 2: Ooty Lake", "Day 3: Doddabetta Peak", "Day 4: Coonoor", "Day 5: Tea Factory", "Day 6: Relax & Departure"],
      budget: "$750",
      transport: "Bus + Car Rental",
      accommodation: "Cottage Stay",
      notes: "Carry a jacket, enjoy fresh tea & chocolates.",
    },
    {
      id: "5",
      name: "Cultural & Food Tour - Kolkata",
      image: require("../../assets/five.jpg"),
      startDate: "2025-05-15",
      endDate: "2025-05-20",
      itinerary: ["Day 1: Victoria Memorial", "Day 2: Howrah Bridge & Park Street", "Day 3: Dakshineswar Temple", "Day 4: Food Tour", "Day 5: Departure"],
      budget: "$650",
      transport: "Flight + Metro",
      accommodation: "Budget Hotel",
      notes: "Try street food, visit bookstores, and enjoy cultural sites.",
    }
  ];
  
  export default listOfTrips;
  